[env:wiscore_rak4631]
platform = nordicnrf52
board = wiscore_rak4631
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit LIS3DH@^1.3.0
    adafruit/Adafruit Unified Sensor@^1.1.14
build_flags =
    ; use CMSIS-NN kernels on Cortex-M
    -DEI_CLASSIFIER_TFLITE_ENABLE_CMSIS_NN=1
