/*
 * Module 7.1 - host-side golden-window test (step 2 of the 4-step ladder).
 *
 * Compiles the SAME features.h + fan_model.h + test_windows.h the firmware
 * uses - on your laptop, no board needed. Generate the headers with
 * train_rf.py first and copy the emlearn include dir (README step 3).
 *
 * Build & run (from platformio/src/):
 *   gcc -DHOST_TEST -I ../lib/emlearn -o /tmp/hosttest host_test.c -lm && /tmp/hosttest
 *
 * The whole file is guarded by HOST_TEST so the PlatformIO target build
 * compiles it to an empty translation unit - do not remove the #ifdef.
 */
#ifdef HOST_TEST

#include <stdio.h>

#include "features.h"
#include "fan_model.h"      /* generated by train_rf.py */
#include "test_windows.h"   /* generated by train_rf.py */

int main(void)
{
    float features[N_FEATURES];
    int failures = 0;

    for (int i = 0; i < TEST_N_WINDOWS; i++) {
        calculate_features(test_windows[i], TEST_WINDOW_LEN, features);
        const int cls = (int)fan_model_predict(features, N_FEATURES);
        const int pass = (cls == test_expected[i]);
        if (!pass) failures++;
        printf("[host] window '%s' -> predicted '%s'  %s\n",
               class_names[test_expected[i]],
               (cls >= 0 && cls < TEST_N_CLASSES) ? class_names[cls] : "?",
               pass ? "PASS" : "FAIL");
    }
    printf("--- %d/%d passed. %s ---\n", TEST_N_WINDOWS - failures, TEST_N_WINDOWS,
           failures ? "Fix before flashing!" : "Proceed to the on-target tests.");
    return failures ? 1 : 0;
}

#endif /* HOST_TEST */
